version: '3'
services:
  fastapi1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FASTAPI_PORT=8000
        - OMP_NUM_THREADS=1
    ports:
      - "8000:8000"
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    cpus: 1
    mem_limit: 2g

  fastapi2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FASTAPI_PORT=8001
        - OMP_NUM_THREADS=-1
    ports:
      - "8001:8001"
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8001"]
    cpus: 1
    mem_limit: 2g
